#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG_MAIN                         102
#define IDD_ABOUTBOX                            103
#define IDR_MAINFRAME                           128
#define IDC_EXIT                                900
#define IDC_LIST_INTERFACES                     1000
#define IDC_EDIT_ID                             1003
#define IDC_UPDATE_FW                           1010
#define IDC_CHECK0_L                            1012
#define IDC_CHECK1_L                            1013
#define IDC_CHECK2_L                            1014
#define IDC_CHECK3_L                            1015
#define IDC_CHECK4_L                            1016
#define IDC_CHECK5_L                            1017
#define IDC_CHECK6_L                            1018
#define IDC_CHECK7_L                            1019
#define IDC_LED_ON                              1020
#define IDC_LED_OFF                             1021
#define IDC_EDIT_PIN5                           1022
#define IDC_EDIT_PIN6                           1023
#define IDC_EDIT_PIN7                           1024
#define IDC_CHECK0_H                            1025
#define IDC_CHECK1_H                            1026
#define IDC_CHECK2_H                            1027
#define IDC_CHECK3_H                            1028
#define IDC_CHECK4_H                            1029
#define IDC_CHECK5_H                            1030
#define IDC_CHECK6_H                            1031
#define IDC_CHECK7_H                            1032
#define IDC_ABOUT                               40000
#define IDC_EDIT_PORT_L                         40001
#define IDC_EDIT_PORT_H                         40002
#define IDC_READ_ID                             40003
#define IDC_WRITE_ID                            40004
#define IDC_TEST_P5                             40005
#define IDC_TEST_P6                             40006
#define IDC_TEST_P7                             40007
